server:
  port: 9093

spring:
  application:
    name: weather-server-2
  ai:
    mcp:
      server:
        name: weather-server-2
        version: 1.0.0
        protocol: STREAMABLE

logging:
  level:
    es.omarall: DEBUG
    io.modelcontextprotocol: INFO
    org.springframework.ai: INFO
